### ISSUE TITLE
ghcjs-perch is not up to date with current ghcjs

### ISSUE THREAD

**Issue by paronsson** [geraldus/ghcjs-perch#1]
> D:\ghcjs-perch\src\Internal\Type.hs:15:33:
>     Module 'GHCJS.Foreign' does not export 'fromJSString'
> 
> D:\ghcjs-perch\src\Internal\Type.hs:16:33:
>     Module 'GHCJS.Types' does not export 'JSArray'

Unfortunately I don't yet understand the internals of ghcjs to know how to update ghjs-perch by myself.

**Comment by geraldus** [comment]
Thanks for the report!
I know, that GHCJS was updated recently, but hadn't chance to dig into details.  I will take care on next week, I hope this is not critical for you.

**Comment by paronsson** [comment]
Thank you very much for your reply and that you are considering looking into the changes done in ghcjs! No it is not critical for me. But I will start using ghcjs-perch when it is ready and I'm looking forward to when hplayground is ported to ghcjs. I think it will be a great development platform for web applications.

**Comment by geraldus** [comment]
Yeah, I wish I had a time to help Alberto with this stuff!
The Perch itself is quite simple.

**Comment by geraldus** [comment]
@paronsson, it turns that I need some time to find out a way to update everything, unfortunatelly there is no migration guide yet from old-base to new improved-base.  Can I ask you about your GHCJS experience?

**Comment by paronsson** [comment]
@geraldus, unfortunately I have just now (last week) started to install ghcjs. That is why I had problems to understand how to update ghcjs-perch. I don't yet have the knowledge about the internals of ghcjs and its' history.

My guess is that there is only need for very few changes but which ones?

This is at least a relevant change in ghcjs:
https://github.com/ghcjs/ghcjs/commit/1cf0238e7fbd9beef0713d723ad0680adaac38a2

**Comment by geraldus** [comment]
I have looked at new GHCJS base, the changes should be quite simple.  I need some time to figure out how can I use GHCJS with stack (formerly I've used GHCJS inside docker container).

**Comment by paronsson** [comment]
That's is great!

Previously i have had problems with installing ghcjs.
But last week I managed to install ghcjs using stack (even om Windows) without a problem using the information on https://github.com/commercialhaskell/stack/blob/master/doc/ghcjs.md

The only problem (which is not a problem here) is that there are a few packages where the version number for libraries used by ghcjs differs from the version used by ghc. So I am hoping for stackage support for ghcjs soon. Then things will be really great!

But as said it works really well right now using the supplied snapshots.

**Comment by geraldus** [comment]
I've looked at new GHCJS' base and it seems that changes will be quite simple.

**Comment by geraldus** [comment]
@paronsson I've pushed an update, but did not tested it much.
