### ISSUE TITLE
Inconsistent licensing information

### ISSUE THREAD

**Issue by peti** [geraldus/ghcjs-perch#20]
The package is licensed under the MIT license according to the Cabal file and the LICENSE file,but https://github.com/geraldus/ghcjs-perch/blob/master/src/GHCJS/Perch.hs claims to be licensed under GPLv3. Is this mismatch intentional?

**Comment by geraldus** [comment]
Thank you, this is mismatch.  Correct licensing is MIT

**Comment by peti** [comment]
Would you mind releasing a point update that fixes this issue so that Stackage can pick it up?

**Comment by geraldus** [comment]
Surely, I will tackle this later today

**Comment by geraldus** [comment]
Done in https://github.com/geraldus/ghcjs-perch/commit/9a08b210bede95445efed7bee135a8a3f993a21e
I will upload new version on Hackage too.
