### ISSUE TITLE
Current hackage does not export newElemNS

### ISSUE THREAD

**Issue by o1lo01ol1o** [geraldus/ghcjs-perch#22]
vis: 

https://github.com/geraldus/ghcjs-perch/blob/master/src/Internal/API.hs#L47
vs
https://hackage.haskell.org/package/ghcjs-perch-0.3.3.2/docs/src/Internal-API.html#newElem

Could a new hackage version be minted?

**Comment by agocorona** [comment]
just sent a pull request that also address that

**Comment by geraldus** [comment]
Merged
