### ISSUE TITLE
Implement transient event handlers

### ISSUE THREAD

**Issue by geraldus** [geraldus/ghcjs-perch#5]
GHCJS supposes that attached callbacks should be released by program, onEven already returns release callback, but `addEvent` does not.
- [ ] implement `onSingleEvent` which will release callback immediately after it was executed first time
- [ ] think how to release callbacks in Perch monad

ping @agocorona

**Comment by agocorona** [comment]
why onEvent release the callback?  I don´t think so. That limitation of GHCJS is very bad for dynamic DOM programming. HPlayground is constantly creating and destroying widgets with callbacks....
